name: Create Newsletter

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NOTION_NEWSLETTER_CONNECTION: ${{ secrets.NOTION_NEWSLETTER_CONNECTION }}
      NOTION_READER_DATABASE_ID: ${{ secrets.NOTION_READER_DATABASE_ID }}
      NOTION_NEWSLETTER_DATABASE_ID: ${{ secrets.NOTION_NEWSLETTER_DATABASE_ID }}
      OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: npm start
